"""Hub ingest endpoint — agents post session metadata after each save.

The agent runs on the robot, writes MCAP files locally, and (when
`hub_url` is configured) POSTs a small JSON blob to this endpoint
describing each saved session. The hub stores the metadata + a URL
pointing back to the agent for on-demand MCAP retrieval.

v2 Phase 1 wiring: see v2-SPEC.md §Phase 1.
"""

from __future__ import annotations

from fastapi import APIRouter, Depends
from pydantic import BaseModel, Field

from ..db import Db, SessionRow, now_ms
from ..ee.alerting import Alerter, AlertEvent
from ..telemetry import Telemetry, rule_from_label


class SessionIngest(BaseModel):
    """Payload posted by the agent after each session save.

    Matches the agent's SessionMetadata + the optional mcap_url
    pointing back at the agent so the hub can stream-proxy on demand.
    Subsystem is optional per Hard Rule 23.
    """

    session_id: str = Field(min_length=1, max_length=200)
    robot_id: str = Field(min_length=1, max_length=200)
    started_at: int = Field(ge=0)
    ended_at: int = Field(ge=0)
    duration_ms: int = Field(ge=0)
    label: str | None = None
    topics: list[str] = Field(default_factory=list)
    mcap_size_bytes: int = Field(ge=0)
    mcap_url: str = Field(
        description="HTTP URL the hub will use to fetch MCAP bytes on demand."
    )
    subsystem: str | None = Field(default=None, max_length=120)
    summary: str | None = Field(
        default=None,
        max_length=8000,
        description=(
            "Structured, deterministic session summary generated by the agent "
            "at save time (v2 P3.5.1). Zero-LLM, works fully offline. Used by "
            "the session UI and the upcoming similarity-search pipeline."
        ),
    )
    agent_url: str | None = Field(
        default=None,
        description="Base URL of the reporting agent (for the agents table).",
    )
    agent_version: str | None = Field(default=None, max_length=40)


class SessionIngestResponse(BaseModel):
    session_id: str
    ingested: bool


def get_router(
    get_db,
    telemetry: Telemetry | None = None,
    alerter: Alerter | None = None,
    cache=None,
) -> APIRouter:
    router = APIRouter(prefix="/api/v1", tags=["ingest"])
    telemetry = telemetry or Telemetry()
    alerter = alerter or Alerter()

    @router.post(
        "/sessions/ingest",
        response_model=SessionIngestResponse,
        summary="Agent posts session metadata to the hub",
    )
    def ingest(
        payload: SessionIngest,
        db: Db = Depends(get_db),
    ) -> SessionIngestResponse:
        """Record an agent-reported session. The MCAP itself stays on the
        agent; this endpoint just stores metadata + the URL to fetch it.

        Also upserts the agents table so heartbeats and ingests share one
        view of which robots have reported in.
        """
        db.upsert_agent(
            robot_id=payload.robot_id,
            agent_url=payload.agent_url,
            agent_version=payload.agent_version,
            subsystem=payload.subsystem,
        )

        # mcap_path stays empty for hub-ingested sessions — the hub does
        # not hold the bytes locally. mcap_url is what matters.
        db.upsert_session(SessionRow(
            id=payload.session_id,
            robot_id=payload.robot_id,
            started_at=payload.started_at,
            ended_at=payload.ended_at,
            duration_ms=payload.duration_ms,
            label=payload.label,
            mcap_path="",
            mcap_size_bytes=payload.mcap_size_bytes,
            topics=payload.topics,
            created_at=now_ms(),
            mcap_url=payload.mcap_url,
            subsystem=payload.subsystem,
            summary=payload.summary,
        ))

        # A new capture changes the dashboard rollup + the similarity corpus —
        # drop the cache so the next read recomputes fresh.
        if cache is not None:
            cache.clear()

        # v2 OTel — opt-in export to the operator's observability stack.
        # No-op unless MD_OTEL_ENDPOINT is configured. prior_occurrences is
        # the fleet-wide count of this same pattern, minus this capture, so
        # the alert can say "Nth occurrence". Telemetry must never break
        # ingest, so failures are swallowed.
        try:
            rule = rule_from_label(payload.label)
            telemetry.record_capture(
                robot_id=payload.robot_id, subsystem=payload.subsystem, rule=rule
            )
            prior = (
                max(0, db.count_by_label(payload.label) - 1) if payload.label else 0
            )
            telemetry.emit_incident(
                session_id=payload.session_id,
                robot_id=payload.robot_id,
                subsystem=payload.subsystem,
                rule=rule,
                summary=payload.summary,
                prior_occurrences=prior,
            )
            # v2 P6 — fire webhook alerts (Slack / PagerDuty / generic).
            # No-op unless a destination is configured. Dispatched on a
            # daemon thread so a slow webhook never delays the ingest reply.
            alerter.alert_capture_in_background(AlertEvent(
                session_id=payload.session_id,
                robot_id=payload.robot_id,
                subsystem=payload.subsystem,
                rule=rule,
                summary=payload.summary,
                prior_occurrences=prior,
            ))
        except Exception:  # pragma: no cover - defensive
            pass

        return SessionIngestResponse(session_id=payload.session_id, ingested=True)

    return router
